services:
  backend:
    container_name: SEP_backend
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/SEPDrive
      SPRING_DATASOURCE_USERNAME: SEPDrive
      SPRING_DATASOURCE_PASSWORD: SEPDriveC7

    networks:
      - SEPdb


  frontend:
    container_name: SEP_frontend
    build: ./frontend/Angular
    ports:
      - "4200:80"

    networks:
      - SEPdb


  db:
    container_name: SEPdb
    image: postgres
    environment:
      POSTGRES_USER: SEPDrive
      POSTGRES_PASSWORD: SEPDriveC7
      PGDATA: /data/postgres
    volumes:
      - SEPdb:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - SEPdb
    restart: unless-stopped

networks:
  SEPdb:
    driver: bridge

volumes:
  SEPdb:




